// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/haton14/ohagi-dinner/ohagi-api/domain"
	"github.com/haton14/ohagi-dinner/ohagi-api/handler"
	"github.com/haton14/ohagi-dinner/ohagi-api/usecase"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeApp(e *echo.Echo, petTokenMaker domain.PetTokenMaker) App {
	auth := usecase.NewAuth(petTokenMaker)
	handlerAuth := handler.NewAuth(e, auth)
	app := NewApp(e, handlerAuth)
	return app
}
